### ISSUE TITLE
学长你好啊，恭喜你们在这场比赛中获得这么好的成绩。请问开源的方案主要是使用了什么方法呢？可以简单分享一下吗？

### ISSUE THREAD

**Issue by JyiHUO** [Shaobo-Xu/ANAC2019#2]
学长你好啊，恭喜你们在这场比赛中获得这么好的成绩。请问开源的方案主要是使用了什么方法呢？可以简单分享一下吗？

**Comment by renph** [comment]
你好，我们用了 类似 borda count 的点数分配方法来估计自己的偏好。然后 利用频率统计估计对手的偏好。协商过程中 逐渐让步，最后妥协

**Comment by JyiHUO** [comment]
谢谢学长，get 到了~
