### ISSUE TITLE
你好，我想问一下在预测自己模型的时候怎么去判断自己模型的正确性，自己的模型怎么去跟真实的效用空间对比呢。

### ISSUE THREAD

**Issue by q13926117923** [Shaobo-Xu/ANAC2019#3]

**Comment by renph** [comment]
这是一个好问题，也是我们没有完全解决的地方。

这里提供两个思路
1. 对比议题Domain下每个issue的相对大小，对比每个issue value的相对大小
2. 对比Bid ranking。把一个bid组合看作整体，对比所有可能的组合的相对大小

以上思路的实现，需要有一个函数能算出两个序列的相似程度，可以参考数学上的**逆序数**计算。

**Comment by q13926117923** [comment]
感谢你的回答
